// services/Doctor.ts

export const DoctorService = {
  async list() {
    // simulate API delay
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve([
          {
            id: "1",
            full_name: "John Smith",
            specialization: "Cardiology",
            qualifications: "MBBS, MD (Cardiology)",
            experience_years: 12,
            bio: "Dr. John Smith is a senior cardiologist with extensive experience in interventional Cardiology.",
            availability: ["Monday", "Wednesday", "Friday"],
            image_url: "https://randomuser.me/api/portraits/men/32.jpg",
            profileImage: { url: "https://randomuser.me/api/portraits/men/32.jpg" },
          },
          {
            id: "2",
            full_name: "Emily Johnson",
            specialization: "Pediatrics",
            qualifications: "MBBS, DCH",
            experience_years: 8,
            bio: "Dr. Emily Johnson specializes in child healthcare and preventive Pediatrics.",
            availability: ["Tuesday", "Thursday"],
            image_url: "https://randomuser.me/api/portraits/women/44.jpg",
            profileImage: { url: "https://randomuser.me/api/portraits/women/44.jpg" },
          },
          {
            id: "3",
            full_name: "Johnson",
            specialization: "Orthopedics",
            qualifications: "MBBS, DCH",
            experience_years: 8,
            bio: "Dr. Emily Johnson specializes in child healthcare and preventive Pediatrics.",
            availability: ["Tuesday", "Thursday"],
            image_url: "https://randomuser.me/api/portraits/men/46.jpg",
            profileImage: { url: "https://randomuser.me/api/portraits/men/46.jpg" },
          },
          {
            id: "4",
            full_name: "John",
            specialization: "Dermatology",
            qualifications: "MBBS, DCH",
            experience_years: 8,
            bio: "Dr. Emily Johnson specializes in child healthcare and preventive Pediatrics.",
            availability: ["Tuesday", "Thursday"],
            image_url: "https://randomuser.me/api/portraits/men/36.jpg",
            profileImage: { url: "https://randomuser.me/api/portraits/men/36.jpg" },
          },
          {
            id: "5",
            full_name: "John",
            specialization: "Neurology",
            qualifications: "MBBS, DCH",
            experience_years: 8,
            bio: "Dr. Emily Johnson specializes in child healthcare and preventive Neurology.",
            availability: ["Tuesday", "Thursday"],
            image_url: "https://randomuser.me/api/portraits/men/51.jpg",
            profileImage: { url: "https://randomuser.me/api/portraits/men/51.jpg" },
          },
        ]);
      }, 800);
    });
  },
};

const generateObjectId = () => Array.from({ length: 24 }, () => '0123456789abcdef'[Math.floor(Math.random() * 16)]).join('');

function generateDoctors() {
  return [
    {
      _id: generateObjectId(),
      fullName: "John Smith",
      department: "Dermatology",
      qualifications: "MBBS, MD",
      experienceYears: 6,
      phone: 36332898993,
      age: 28,
      address: "123 Main St, Tokyo",
      availableDays: ["Monday", "Tuesday", "Wednesday"],
      availableTimes: "09:00-17:00",
      bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
      appointments: [],
      description:
        "Dr. John Smith specializes in child healthcare and preventive Neurology.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/32.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Emily Johnson",
      department: "Cardiology",
      qualifications: "MBBS, DM",
      experienceYears: 10,
      phone: 36332987456,
      age: 35,
      address: "22 Heart Ave, Osaka",
      availableDays: ["Tuesday", "Thursday", "Friday"],
      availableTimes: "10:00-18:00",
      bio: "Emily Johnson is an expert in cardiovascular diseases and non-invasive cardiac procedures with a strong academic background.",
      appointments: [],
      description:
        "Expert in cardiovascular diseases and non-invasive cardiac procedures.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/44.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Michael Brown",
      department: "Orthopedics",
      qualifications: "MBBS, MS (Ortho)",
      experienceYears: 8,
      phone: 36333765432,
      age: 33,
      address: "45 Ortho Lane, Kyoto",
      availableDays: ["Monday", "Wednesday", "Friday"],
      availableTimes: "09:30-16:30",
      bio: "Michael Brown specializes in joint replacement and sports injury rehabilitation, helping patients return to their active lifestyles.",
      appointments: [],
      description:
        "Specializes in joint replacement and sports injury rehabilitation.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/46.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Sarah Davis",
      department: "Neurology",
      qualifications: "MBBS, MD (Neuro)",
      experienceYears: 12,
      phone: 36332112345,
      age: 40,
      address: "87 Neuro Blvd, Tokyo",
      availableDays: ["Monday", "Thursday"],
      availableTimes: "08:00-15:00",
      bio: "Sarah Davis focuses on neurological disorders and neuro-rehabilitation with more than a decade of experience.",
      appointments: [],
      description:
        "Focuses on neurological disorders and neuro-rehabilitation.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/12.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Daniel Wilson",
      department: "Pediatrics",
      qualifications: "MBBS, DCH",
      experienceYears: 5,
      phone: 36332299887,
      age: 29,
      address: "10 Sakura Rd, Yokohama",
      availableDays: ["Monday", "Tuesday", "Friday"],
      availableTimes: "09:00-17:00",
      bio: "Daniel Wilson is dedicated to child wellness, immunization, and pediatric nutrition.",
      appointments: [],
      description: "Dedicated to child wellness and pediatric nutrition.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/64.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Olivia Martinez",
      department: "Gynecology",
      qualifications: "MBBS, MS (OBG)",
      experienceYears: 7,
      phone: 36332564783,
      age: 31,
      address: "76 Blossom St, Nagoya",
      availableDays: ["Tuesday", "Thursday", "Saturday"],
      availableTimes: "10:00-18:00",
      bio: "Olivia Martinez is a specialist in women’s health, prenatal and postnatal care.",
      appointments: [],
      description: "Specialist in women’s health, prenatal and postnatal care.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/28.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "William Anderson",
      department: "ENT",
      qualifications: "MBBS, DLO",
      experienceYears: 9,
      phone: 36332458990,
      age: 34,
      address: "33 Harmony Rd, Fukuoka",
      availableDays: ["Wednesday", "Thursday", "Friday"],
      availableTimes: "09:00-16:00",
      bio: "William Anderson is an expert in ear, nose, and throat disorders and endoscopic surgeries.",
      appointments: [],
      description:
        "Expert in ear, nose, and throat disorders and endoscopic surgeries.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/81.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Ava Thomas",
      department: "Dermatology",
      qualifications: "MBBS, DDVL",
      experienceYears: 4,
      phone: 36332900988,
      age: 27,
      address: "11 River St, Kobe",
      availableDays: ["Monday", "Tuesday", "Thursday"],
      availableTimes: "09:30-17:30",
      bio: "Ava Thomas is experienced in skincare treatments, acne management, and cosmetic Dermatology.",
      appointments: [],
      description: "Experienced in skincare treatments and cosmetic Dermatology.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/17.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "James Taylor",
      department: "Urology",
      qualifications: "MBBS, MCh (Urology)",
      experienceYears: 11,
      phone: 36332214567,
      age: 38,
      address: "5 Greenhill, Tokyo",
      availableDays: ["Monday", "Wednesday", "Saturday"],
      availableTimes: "10:00-17:00",
      bio: "James Taylor specializes in urinary tract disorders, kidney stones, and prostate treatments.",
      appointments: [],
      description:
        "Specializes in urinary tract disorders and prostate treatments.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/36.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Mia Moore",
      department: "Psychiatry",
      qualifications: "MBBS, MD (Psych)",
      experienceYears: 6,
      phone: 36332199812,
      age: 30,
      address: "19 Peace Ave, Osaka",
      availableDays: ["Tuesday", "Thursday", "Friday"],
      availableTimes: "09:00-17:00",
      bio: "Mia Moore focuses on mental health, anxiety, depression, and mood disorder management.",
      appointments: [],
      description:
        "Focuses on mental health, anxiety, and mood disorder management.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/68.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Ethan Lee",
      department: "Oncology",
      qualifications: "MBBS, DM (Oncology)",
      experienceYears: 13,
      phone: 36332655443,
      age: 41,
      address: "4 Hope St, Hiroshima",
      availableDays: ["Monday", "Wednesday"],
      availableTimes: "08:00-15:00",
      bio: "Ethan Lee is highly experienced in cancer diagnosis, chemotherapy, and compassionate patient counseling.",
      appointments: [],
      description:
        "Experienced in cancer diagnosis, chemotherapy, and patient counseling.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/51.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Isabella Harris",
      department: "Ophthalmology",
      qualifications: "MBBS, MS (Ophth)",
      experienceYears: 9,
      phone: 36332777891,
      age: 33,
      address: "8 Light St, Yokohama",
      availableDays: ["Wednesday", "Thursday", "Friday"],
      availableTimes: "10:00-18:00",
      bio: "Isabella Harris is a specialist in cataract surgery, refractive errors, and vision correction treatments.",
      appointments: [],
      description:
        "Specialist in cataract surgery and vision correction treatments.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/33.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Benjamin Clark",
      department: "Dentistry",
      qualifications: "BDS, MDS",
      experienceYears: 7,
      phone: 36332887654,
      age: 32,
      address: "56 Smile Rd, Tokyo",
      availableDays: ["Monday", "Tuesday", "Thursday"],
      availableTimes: "09:00-17:00",
      bio: "Benjamin Clark is an expert in restorative dentistry, root canals, and minor oral surgery.",
      appointments: [],
      description: "Expert in restorative dentistry and oral surgery.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/22.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Charlotte Lewis",
      department: "Radiology",
      qualifications: "MBBS, MD (Radiology)",
      experienceYears: 10,
      phone: 36332654390,
      age: 36,
      address: "72 Scan Blvd, Nagasaki",
      availableDays: ["Tuesday", "Thursday"],
      availableTimes: "08:00-16:00",
      bio: "Charlotte Lewis is highly experienced in MRI, CT scans, ultrasound, and diagnostic imaging interpretation.",
      appointments: [],
      description: "Experienced in MRI, CT scans, and diagnostic imaging.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/90.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Alexander Walker",
      department: "General_Medicine",
      qualifications: "MBBS",
      experienceYears: 5,
      phone: 36332876543,
      age: 29,
      address: "14 Health St, Tokyo",
      availableDays: ["Monday", "Wednesday", "Friday"],
      availableTimes: "09:00-17:00",
      bio: "Alexander Walker provides compassionate primary care, regular health check-ups, and preventive medicine.",
      appointments: [],
      description: "Provides primary care and preventive health services.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/75.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Grace Hall",
      department: "Endocrinology",
      qualifications: "MBBS, DM (Endocrinology)",
      experienceYears: 12,
      phone: 36332456712,
      age: 39,
      address: "22 Sugar Rd, Kyoto",
      availableDays: ["Tuesday", "Thursday"],
      availableTimes: "10:00-18:00",
      bio: "Grace Hall specializes in diabetes management, thyroid disorders, and hormonal imbalance treatment.",
      appointments: [],
      description: "Specializes in diabetes and hormonal imbalance management.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/49.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Lucas Allen",
      department: "Nephrology",
      qualifications: "MBBS, DM (Nephrology)",
      experienceYears: 8,
      phone: 36332678901,
      age: 34,
      address: "33 Kidney Ave, Osaka",
      availableDays: ["Wednesday", "Friday", "Saturday"],
      availableTimes: "09:00-17:00",
      bio: "Lucas Allen focuses on kidney care, hypertension, and dialysis treatment management.",
      appointments: [],
      description: "Focuses on kidney care and dialysis treatment management.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/82.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Harper Young",
      department: "Gastroenterology",
      qualifications: "MBBS, DM (Gastro)",
      experienceYears: 10,
      phone: 36332198765,
      age: 37,
      address: "17 Digest Rd, Kobe",
      availableDays: ["Monday", "Tuesday", "Thursday"],
      availableTimes: "10:00-17:00",
      bio: "Harper Young is an expert in digestive system disorders, liver diseases, and diagnostic endoscopy.",
      appointments: [],
      description:
        "Expert in digestive system disorders and endoscopy procedures.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/55.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Henry King",
      department: "Pulmonology",
      qualifications: "MBBS, MD (Pulmo)",
      experienceYears: 11,
      phone: 36332789012,
      age: 38,
      address: "27 Airway St, Sapporo",
      availableDays: ["Monday", "Wednesday", "Friday"],
      availableTimes: "09:00-16:00",
      bio: "Henry King is a pulmonologist specializing in respiratory diseases, asthma, COPD, and sleep disorders.",
      appointments: [],
      description: "Specialist in respiratory diseases and allergy treatment.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/15.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Sofia Wright",
      department: "Rheumatology",
      qualifications: "MBBS, MD (Rheumatology)",
      experienceYears: 9,
      phone: 36332800987,
      age: 35,
      address: "55 Joint St, Tokyo",
      availableDays: ["Tuesday", "Thursday"],
      availableTimes: "10:00-18:00",
      bio: "Sofia Wright is an expert in autoimmune diseases, arthritis, and complex musculoskeletal disorders.",
      appointments: [],
      description: "Expert in autoimmune and musculoskeletal disorders.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/22.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Dr. John Smith",
      department: "Cardiology",
      qualifications: "MBBS, MD",
      experienceYears: 10,
      phone: 1234567890,
      age: 40,
      address: "Tokyo, Japan",
      availableDays: ["Monday", "Wednesday", "Friday"],
      availableTimes: "9:00-17:00",
      bio: "Dr. John Smith is a leading cardiologist specializing in heart and vascular conditions.",
      appointments: [],
      description: "Specializes in heart and vascular conditions.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/33.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Dr. Emily Brown",
      department: "Neurology",
      qualifications: "MBBS, DM",
      experienceYears: 8,
      phone: 9876543210,
      age: 35,
      address: "Osaka, Japan",
      availableDays: ["Tuesday", "Thursday"],
      availableTimes: "10:00-18:00",
      bio: "Dr. Emily Brown is an expert in brain and nerve disorders, dedicated to neuro-rehabilitation.",
      appointments: [],
      description: "Expert in brain and nerve disorders.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/45.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Dr. David Lee",
      department: "Orthopedics",
      qualifications: "MBBS, MS",
      experienceYears: 7,
      phone: 7777777777,
      age: 36,
      address: "Nagoya, Japan",
      availableDays: ["Monday", "Tuesday"],
      availableTimes: "9:00-17:00",
      bio: "Dr. David Lee is a specialist in bone and joint care, focusing on minimal invasive surgeries.",
      appointments: [],
      description: "Specialist in bone and joint care.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/67.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Dr. Sarah Kim",
      department: "Pediatrics",
      qualifications: "MBBS, DCH",
      experienceYears: 5,
      phone: 8888888888,
      age: 32,
      address: "Fukuoka, Japan",
      availableDays: ["Wednesday", "Friday"],
      availableTimes: "8:30-16:30",
      bio: "Dr. Sarah Kim is dedicated to children's health, development, and preventive pediatrics.",
      appointments: [],
      description: "Dedicated to children’s health and development.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/62.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Dr. Laura Tanaka",
      department: "Dermatology",
      qualifications: "MBBS, MD",
      experienceYears: 6,
      phone: 9999999999,
      age: 33,
      address: "Kyoto, Japan",
      availableDays: ["Monday", "Thursday"],
      availableTimes: "9:00-17:00",
      bio: "Dr. Laura Tanaka is a skin and cosmetic care expert, specializing in clinical dermatology.",
      appointments: [],
      description: "Skin and cosmetic care expert.",
      profileImage: { url: "https://randomuser.me/api/portraits/women/82.jpg" },
    },
    {
      _id: generateObjectId(),
      fullName: "Dr. Hiroshi Sato",
      department: "General_Medicine",
      qualifications: "MBBS",
      experienceYears: 12,
      phone: 1212121212,
      age: 45,
      address: "Tokyo, Japan",
      availableDays: ["Monday", "Tuesday", "Thursday"],
      availableTimes: "9:00-18:00",
      bio: "Dr. Hiroshi Sato provides general diagnosis, primary medical treatments, and health counseling.",
      appointments: [],
      description: "Provides general diagnosis and treatment.",
      profileImage: { url: "https://randomuser.me/api/portraits/men/91.jpg" },
    },
  ];
}

export const allDoctors = generateDoctors();
