export const doctorsData = [
  {
    // _id: "6715c8a10f1d9c0012a1b00156",
    fullName: "John Smith",
    email: "johnsmith@gmail.com",
    password: "johnsmith",
    department: "Dermatology",
    qualifications: "MBBS, MD",
    experienceYears: 6,
    phone: "36332898993",
    age: 28,
    address: "123 Main St, Tokyo",
    availableDays: ["Monday", "Tuesday", "Wednesday"],
    availableTimes: "09:00-17:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description:
      "Dr. John Smith specializes in child healthcare and preventive Neurology.",
  },
  {
    // _id: "6715c8a10f1d9c0012a1b002279",
    fullName: "Emily Johnson",
    email: "emilyjohnson@gmail.com",
    password: "emilyjohnson",
    department: "Cardiology",
    qualifications: "MBBS, DM",
    experienceYears: 10,
    phone: "36332987456",
    age: 35,
    address: "22 Heart Ave, Osaka",
    availableDays: ["Tuesday", "Thursday", "Friday"],
    availableTimes: "10:00-18:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description:
      "Expert in cardiovascular diseases and non-invasive cardiac procedures.",
  },
  {
    // _id: "6715c8a10f1d9c0012a1b003094",
    fullName: "Michael Brown",
    email: "michaelbrown@gmail.com",
    password: "michaelbrown",

    department: "Orthopedics",
    qualifications: "MBBS, MS (Ortho)",
    experienceYears: 8,
    phone: "36333765432",
    age: 33,
    address: "45 Ortho Lane, Kyoto",
    availableDays: ["Monday", "Wednesday", "Friday"],
    availableTimes: "09:30-16:30",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description:
      "Specializes in joint replacement and sports injury rehabilitation.",
  },
  {
    // _id: "6715c8a10f1d9c0012a1b004274",
    fullName: "Sarah Davis",
    email: "sarahdavis@gmail.com",
    password: "sarahdavis",
    department: "Neurology",
    qualifications: "MBBS, MD (Neuro)",
    experienceYears: 12,
    phone: "36332112345",
    age: 40,
    address: "87 Neuro Blvd, Tokyo",
    availableDays: ["Monday", "Thursday"],
    availableTimes: "08:00-15:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Focuses on neurological disorders and neuro-rehabilitation.",
  },
  {
    // _id: "6715c8a10f1d9c0012a1b892398005",
    fullName: "Daniel Wilson",
    email: "danielwilson@gmail.com",
    password: "danielwilson",
    department: "Pediatrics",
    qualifications: "MBBS, DCH",
    experienceYears: 5,
    phone: "36332299887",
    age: 29,
    address: "10 Sakura Rd, Yokohama",
    availableDays: ["Monday", "Tuesday", "Friday"],
    availableTimes: "09:00-17:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Dedicated to child wellness and pediatric nutrition.",
  },
  {
    // _id: "6715c8a10f1d9c0012a1b00620937",
    fullName: "Olivia Martinez",
    email: "oliviamartinez@gmail.com",
    password: "oliviamartinez",
    department: "Gynecology",
    qualifications: "MBBS, MS (OBG)",
    experienceYears: 7,
    phone: "36332564783",
    age: 31,
    address: "76 Blossom St, Nagoya",
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    availableTimes: "10:00-18:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Specialist in women’s health, prenatal and postnatal care.",
  },
  {
    // _id: "6715c8a10f1d9c00132932a1b007",
    fullName: "William Anderson",
    email: "williamanderson@gmail.com",
    password: "williamanderson",
    department: "ENT",
    qualifications: "MBBS, DLO",
    experienceYears: 9,
    phone: "36332458990",
    age: 34,
    address: "33 Harmony Rd, Fukuoka",
    availableDays: ["Wednesday", "Thursday", "Friday"],
    availableTimes: "09:00-16:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description:
      "Expert in ear, nose, and throat disorders and endoscopic surgeries.",
  },
  {
    // _id: "6715c8a10f1d9c0019832a1b008",
    fullName: "Ava Thomas",
    email: "avathomas@gmail.com",
    password: "avathomas",
    department: "Dermatology",
    qualifications: "MBBS, DDVL",
    experienceYears: 4,
    phone: "36332900988",
    age: 27,
    address: "11 River St, Kobe",
    availableDays: ["Monday", "Tuesday", "Thursday"],
    availableTimes: "09:30-17:30",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Experienced in skincare treatments and cosmetic Dermatology.",
  },
  {
    // _id: "6715c8a10f1d9c00120282a1b009",
    fullName: "James Taylor",
    email: "jamestaylor@gmail.com",
    password: "jamestaylor",
    department: "Urology",
    qualifications: "MBBS, MCh (Urology)",
    experienceYears: 11,
    phone: "36332214567",
    age: 38,
    address: "5 Greenhill, Tokyo",
    availableDays: ["Monday", "Wednesday", "Saturday"],
    availableTimes: "10:00-17:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description:
      "Specializes in urinary tract disorders and prostate treatments.",
  },
  {
    // _id: "6715c8a102345f1d9c0012a1b00a",
    fullName: "Mia Moore",
    email: "miamoore@gmail.com",
    password: "miamoore",
    department: "Psychiatry",
    qualifications: "MBBS, MD (Psych)",
    experienceYears: 6,
    phone: "36332199812",
    age: 30,
    address: "19 Peace Ave, Osaka",
    availableDays: ["Tuesday", "Thursday", "Friday"],
    availableTimes: "09:00-17:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description:
      "Focuses on mental health, anxiety, and mood disorder management.",
  },
  {
    // _id: "6715c8a10f1d9c0012982a1b00b",
    fullName: "Ethan Lee",
    email: "ethanlee@gmail.com",
    password: "ethanlee",
    department: "Oncology",
    qualifications: "MBBS, DM (Oncology)",
    experienceYears: 13,
    phone: "36332655443",
    age: 41,
    address: "4 Hope St, Hiroshima",
    availableDays: ["Monday", "Wednesday"],
    availableTimes: "08:00-15:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description:
      "Experienced in cancer diagnosis, chemotherapy, and patient counseling.",
  },
  {
    // _id: "6715c8a10f1d9c0012512a1b00c",
    fullName: "Isabella Harris",
    email: "isabellaharris@gmail.com",
    password: "isabellaharris",
    department: "Ophthalmology",
    qualifications: "MBBS, MS (Ophth)",
    experienceYears: 9,
    phone: "36332777891",
    age: 33,
    address: "8 Light St, Yokohama",
    availableDays: ["Wednesday", "Thursday", "Friday"],
    availableTimes: "10:00-18:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description:
      "Specialist in cataract surgery and vision correction treatments.",
  },
  {
    // _id: "6715c8a10f1d9c09830012a1b00d",
    fullName: "Benjamin Clark",
    email: "benjaminclark@gmail.com",
    password: "benjaminclark",
    department: "Dentistry",
    qualifications: "BDS, MDS",
    experienceYears: 7,
    phone: "36332887654",
    age: 32,
    address: "56 Smile Rd, Tokyo",
    availableDays: ["Monday", "Tuesday", "Thursday"],
    availableTimes: "09:00-17:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Expert in restorative dentistry and oral surgery.",
  },
  {
    // _id: "6715c8a10f1d9c10290012a1b00e",
    fullName: "Charlotte Lewis",
    email: "charlottelewis@gmail.com",
    password: "charlottelewis",
    department: "Radiology",
    qualifications: "MBBS, MD (Radiology)",
    experienceYears: 10,
    phone: "36332654390",
    age: 36,
    address: "72 Scan Blvd, Nagasaki",
    availableDays: ["Tuesday", "Thursday"],
    availableTimes: "08:00-16:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Experienced in MRI, CT scans, and diagnostic imaging.",
  },
  {
    // _id: "6715c8a10f13972d9c0012a1b00f",
    fullName: "Alexander Walker",
    email: "alexanderwalker@gmail.com",
    password: "alexanderwalker",
    department: "General_Medicine",
    qualifications: "MBBS",
    experienceYears: 5,
    phone: "36332876543",
    age: 29,
    address: "14 Health St, Tokyo",
    availableDays: ["Monday", "Wednesday", "Friday"],
    availableTimes: "09:00-17:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Provides primary care and preventive health services.",
  },
  {
    // _id: "6715c8a10f1d29839c0012a1b010",
    fullName: "Grace Hall",
    email: "gracehall@gmail.com",
    password: "gracehall",
    department: "Endocrinology",
    qualifications: "MBBS, DM (Endocrinology)",
    experienceYears: 12,
    phone: "36332456712",
    age: 39,
    address: "22 Sugar Rd, Kyoto",
    availableDays: ["Tuesday", "Thursday"],
    availableTimes: "10:00-18:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Specializes in diabetes and hormonal imbalance management.",
  },
  {
    // _id: "6715c8a10f1d93928c0012a1b011",
    fullName: "Lucas Allen",
    email: "lucasallen@gmail.com",
    password: "lucasallen",
    department: "Nephrology",
    qualifications: "MBBS, DM (Nephrology)",
    experienceYears: 8,
    phone: "36332678901",
    age: 34,
    address: "33 Kidney Ave, Osaka",
    availableDays: ["Wednesday", "Friday", "Saturday"],
    availableTimes: "09:00-17:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Focuses on kidney care and dialysis treatment management.",
  },
  {
    // _id: "6715c8a10f1d9c0012a1w938b012",
    fullName: "Harper Young",
    email: "harperyoung@gmail.com",
    password: "harperyoung",
    department: "Gastroenterology",
    qualifications: "MBBS, DM (Gastro)",
    experienceYears: 10,
    phone: "36332198765",
    age: 37,
    address: "17 Digest Rd, Kobe",
    availableDays: ["Monday", "Tuesday", "Thursday"],
    availableTimes: "10:00-17:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description:
      "Expert in digestive system disorders and endoscopy procedures.",
  },
  {
    // _id: "6715c8a10f1d9c0039212a1b013",
    fullName: "Henry King",
    email: "henryking@gmail.com",
    password: "henryking",
    department: "Pulmonology",
    qualifications: "MBBS, MD (Pulmo)",
    experienceYears: 11,
    phone: "36332789012",
    age: 38,
    address: "27 Airway St, Sapporo",
    availableDays: ["Monday", "Wednesday", "Friday"],
    availableTimes: "09:00-16:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Specialist in respiratory diseases and allergy treatment.",
  },
  {
    // _id: "6715c8a10f1d9c20920012a1b014",
    fullName: "Sofia Wright",
    email: "sofiawright@gmail.com",
    password: "sofiawright",
    department: "Rheumatology",
    qualifications: "MBBS, MD (Rheumatology)",
    experienceYears: 9,
    phone: "36332800987",
    age: 35,
    address: "55 Joint St, Tokyo",
    availableDays: ["Tuesday", "Thursday"],
    availableTimes: "10:00-18:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Expert in autoimmune and musculoskeletal disorders.",
  },

  {
    // _id: "2129373",
    fullName: "Emily Brown",
    email: "emilybrown@gmail.com",
    password: "emilybrown",
    department: "Neurology",
    qualifications: "MBBS, DM",
    experienceYears: 8,
    phone: "9876543210",
    age: 35,
    address: "Osaka, Japan",
    availableDays: ["Tuesday", "Thursday"],
    availableTimes: "10:00-18:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Expert in brain and nerve disorders.",
  },
  {
    // _id: "3129384",
    fullName: "David Lee",
    email: "davidlee@gmail.com",
    password: "davidlee",
    department: "Orthopedics",
    qualifications: "MBBS, MS",
    experienceYears: 7,
    phone: "7777777777",
    age: 36,
    address: "Nagoya, Japan",
    availableDays: ["Monday", "Tuesday"],
    availableTimes: "9:00-17:00",
    bio: "John Smith has been practicing dermatology for 6 years, focusing on both medical and cosmetic skin treatments.",
    appointments: [],
    description: "Specialist in bone and joint care.",
  },
];
